spring:
  application:
    name: appcat
server:
  port: 80

---
spring:
  profiles:
    active: local

---
spring:
  profiles:
    active: kubernetes
  datasource:
    url: jdbc:postgresql://${SECRET_DB_HOST:defhost}:5432/postgres
    username: ${SECRET_DB_USERNAME:defun}
    password: ${SECRET_DB_PASSWORD:defpw}
    platform: postgres
    initialization-mode: always
    continue-on-error: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
    database: postgresql
