apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: appcat
  name: appcat
spec:
  replicas: 2
  selector:
    matchLabels:
      run: appcat
  template:
    metadata:
      labels:
        run: appcat
    spec:
      containers:
      - image: gcr.io/appcat/appcat:latest
        name: appcat
        ports:
        - containerPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: appcatgetter
  name: appcatgetter
spec:
  replicas: 2
  selector:
    matchLabels:
      run: appcatgetter
  template:
    metadata:
      labels:
        run: appcatgetter
    spec:
      containers:
      - image: gcr.io/appcatgetter/appcatgetter:latest
        name: appcatgetter
        ports:
        - containerPort: 2020