kind: Service
apiVersion: v1
metadata:
  name: appcat
spec:
  selector:
     run: appcat
  ports:
  - protocol: TCP
    port: 786
    targetPort: 80
  type: LoadBalancer

---

kind: Service
apiVersion: v1
metadata:
  name: appcatgetter
spec:
  selector:
     run: appcatgetter
  ports:
  - protocol: TCP
    port: 2020
    targetPort: 10001
  type: LoadBalancer